In [1]:
# Exp :- 12

In [2]:
# Aim : To perform Operation of KNN classifiers

In [1]:
#Name:vedant ingole
#Roll:71
#sec:C
#subject:DSS
#Date:

In [2]:
import pandas as pd                                                                # Importing the Libraries
import numpy as np

In [3]:
import os                                                                          # Data acquisitionuing Pandas

In [9]:
os.getcwd()

'/Users/vedantingole/Desktop'

In [10]:
os.chdir("/Users/vedantingole/Desktop")

In [11]:
data=pd.read_csv("Iris.csv")

In [12]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [13]:
data.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [15]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [16]:
data.shape

(150, 6)

In [17]:
data.size

900

In [18]:
data.ndim

2

In [19]:
data.isna()

        Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0    False          False         False          False         False    False
1    False          False         False          False         False    False
2    False          False         False          False         False    False
3    False          False         False          False         False    False
4    False          False         False          False         False    False
..     ...            ...           ...            ...           ...      ...
145  False          False         False          False         False    False
146  False          False         False          False         False    False
147  False          False         False          False         False    False
148  False          False         False          False         False    False
149  False          False         False          False         False    False

[150 rows x 6 columns]

In [20]:
data.isna().any()                                                                        # Data preprocessing _ data cleaning _ missing value treatment

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [21]:
data.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [22]:
x=data.drop("Species", axis=1)                                                           #Independent and Dependent Variables
y=data["Species"]

In [23]:
from sklearn.model_selection import train_test_split                                     #splitting the data into training and testing data sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2 ,random_state=42)

In [24]:
from sklearn.neighbors import KNeighborsClassifier                                       # KNN Classifier
from sklearn.metrics import accuracy_score

In [25]:
knn=KNeighborsClassifier()

In [26]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [27]:
y_pred2=knn.predict(x_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred2)

In [29]:
accuracy

1.0